spring:
  datasource:
    url: jdbc:mysql://117.50.163.249/video_delivery_web_db?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: hzau.123
    driver-class-name: com.mysql.cj.jdbc.Driver

#设置端口
server :
  port : 8088