spring:
  datasource:
    url: jdbc:mysql://localhost/video_delivery_web_db?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: Qkn2695946524
    driver-class-name: com.mysql.cj.jdbc.Driver

#设置端口
server :
  port : 8088

